CFG = {
    "empresas": {
        "nc": {
            "id": "nc",
            "nome": "Nutricash",
            "razao": "NUTRICASH LTDA",
            "hdr": "#1C3557",
            "acc": "#2196C4",
            "acc_light": "#E3F4FA",
            "desc": "Benefícios, alimentação e gestão de pagamentos corporativos",
        },
        "mf": {
            "id": "mf",
            "nome": "MaxiFrota",
            "razao": "MAXIFROTA LTDA",
            "hdr": "#003D78",
            "acc": "#F5A800",
            "acc_light": "#FFF8E1",
            "desc": "Gestão de frotas, abastecimento e mobilidade corporativa",
        },
    },
    "contas": [
        # ── ATIVO ──────────────────────────────────────────────
        {
            "id": "adto-forn",
            "nome": "Adiantamento a Fornecedores",
            "codigo": "18805000003",
            "tipo": "ativo",
            "icon": "🏭",
            "empresas": ["nc", "mf"],
            "campos": ["Saldo Relatório Auxiliar (Contas a Pagar)", "Saldo Razão"],
            "wip": False,
        },
        {
            "id": "adto-fer",
            "nome": "Adiantamento de Férias",
            "codigo": "18803000003",
            "tipo": "ativo",
            "icon": "🏖️",
            "empresas": ["nc", "mf"],
            "campos": ["Saldo Inicial", "Adiantamentos do Período", "Baixas (Folha)", "Saldo Razão"],
            "wip": False,
        },
        {
            "id": "adto-sal",
            "nome": "Adiantamento de Salários",
            "codigo": "18803000001",
            "tipo": "ativo",
            "icon": "💼",
            "empresas": ["nc", "mf"],
            "campos": ["Saldo Inicial", "Adiantamentos do Período", "Baixas (Folha)", "Saldo Razão"],
            "wip": False,
        },
        {
            "id": "irrf-antec",
            "nome": "IRRF Antecipado",
            "codigo": "18845100003",
            "tipo": "ativo",
            "icon": "💰",
            "empresas": ["nc", "mf"],
            "campos": ["Saldo Inicial", "Retenções do Período", "Compensações / Baixas", "Saldo Razão"],
            "wip": False,
        },
        # ── PASSIVO ────────────────────────────────────────────
        {
            "id": "irrf-serv",
            "nome": "IRRF s/ Serviços a Recolher",
            "codigo": "49420100001",
            "tipo": "passivo",
            "icon": "📋",
            "empresas": ["nc", "mf"],
            "campos": ["Saldo Inicial", "IRRF Retido no Período", "Recolhimentos (DARF)", "Saldo Razão"],
            "wip": False,
        },
        {
            "id": "irrf-com",
            "nome": "IRRF s/ Comissões a Recolher",
            "codigo": "49420100002",
            "tipo": "passivo",
            "icon": "📋",
            "empresas": ["nc", "mf"],
            "campos": ["Saldo Inicial", "IRRF Retido no Período", "Recolhimentos (DARF)", "Saldo Razão"],
            "wip": False,
        },
        {
            "id": "pis",
            "nome": "PIS a Recolher",
            "codigo": "49420900001",
            "tipo": "passivo",
            "icon": "🔖",
            "empresas": ["nc", "mf"],
            "campos": ["Saldo Inicial", "PIS Apurado", "Recolhimentos", "Saldo Razão"],
            "wip": False,
        },
        {
            "id": "cofins",
            "nome": "COFINS a Recolher",
            "codigo": "49420900002",
            "tipo": "passivo",
            "icon": "🔖",
            "empresas": ["nc", "mf"],
            "campos": ["Saldo Inicial", "COFINS Apurado", "Recolhimentos", "Saldo Razão"],
            "wip": False,
        },
        {
            "id": "iss",
            "nome": "ISS a Recolher",
            "codigo": "49420900003",
            "tipo": "passivo",
            "icon": "🏙️",
            "empresas": ["nc", "mf"],
            "campos": ["Saldo Inicial", "ISS Apurado", "Recolhimentos", "Saldo Razão"],
            "wip": False,
        },
        {
            "id": "forn",
            "nome": "Fornecedores",
            "codigo": "49992000001",
            "tipo": "passivo",
            "icon": "🤝",
            "empresas": ["nc", "mf"],
            "campos": ["Saldo Inicial", "NF Recebidas", "Pagamentos Realizados", "Saldo Razão"],
            "wip": False,
        },
        {
            "id": "rede-conv",
            "nome": "Rede Conveniada a Pagar",
            "codigo": "49992000002",
            "tipo": "passivo",
            "icon": "🏪",
            "empresas": ["nc"],
            "campos": ["Saldo Inicial", "Transações do Período", "Repasses Realizados", "Saldo Razão"],
            "wip": False,
        },
        {
            "id": "moeda-pat",
            "nome": "Moeda Eletrônica PAT Papel",
            "codigo": "49992000022",
            "tipo": "passivo",
            "icon": "🃏",
            "empresas": ["nc"],
            "campos": ["Saldo Inicial", "Emissões do Período", "Resgates / Utilizações", "Saldo Razão"],
            "wip": False,
        },
        {
            "id": "moeda-frt",
            "nome": "Moeda Eletrônica Frota Papel",
            "codigo": "49992000023",
            "tipo": "passivo",
            "icon": "⛽",
            "empresas": ["mf"],
            "campos": ["Saldo Inicial", "Emissões do Período", "Resgates / Utilizações", "Saldo Razão"],
            "wip": False,
        },
    ],
}
